
# http协议端口 server是https协议端口
http:
  port: 8881
server:
  port: 6661
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 654321
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true #开启https协议端口
debug: false #开启调试模式与否

spring:
  application:
      name: springStudyPinYin
#  profiles:
#    active: other
  main:
    banner-mode: "OFF"

  datasource:
    url: jdbc:mysql://192.168.201.43:6036/medical_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=Shanghai
    username: root                                      #数据库用户名
    password: Ggkj_1688                                    #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    root: info
    # logging.level.mapper类所在包位置=debug mybatis打印sql语句
    github.com.bobgit.study.pinyin.dao: debug
#    github.com.bobgit.study.pinyin.interceptor: info
    org:
      springframework:
        security: info
        web: info

#范围路径 比如：/admin
adminPath:
interceptor:
  # 后台管理记录拦截器
  enabled: true
  addPathPatterns: >
    ${adminPath}/**
  excludePathPatterns: >
    ${adminPath}/patient,
    ${adminPath}/rongCloud/**,
    ${adminPath}/desktop,
    ${adminPath}/sys/online/count,
    ${adminPath}/**/treeData,
    ${adminPath}/file/**,
    ${adminPath}/tags/*,
    ${adminPath}/msg/**





