
# http协议端口 server是https协议端口
http:
  port: 8881
server:
  port: 6661
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 654321
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true #开启https协议端口
debug: false #开启调试模式与否

spring:
  application:
      name: springStudyPinYin
  profiles:
    active: dev
  main:
    banner-mode: "OFF"

#  jmx:
#    enabled: false # default:true Registering beans for JMX exposure on startup

  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
#    username: root                                      #数据库用户名
#    password: root                                    #数据库密码
#    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      one:  #数据源1
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
        username: root                                      #数据库用户名
        password: root                                    #数据库密码
#        driver-class-name: com.mysql.cj.jdbc.Driver

      two: #数据源2
        url: jdbc:mysql://localhost:3306/medical?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
        username: root                                      #数据库用户名
        password: root                                    #数据库密码
#        driver-class-name: com.mysql.cj.jdbc.Driver


      three: #数据源3
        url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
        username: root                                      #数据库用户名
        password: root                                    #数据库密码
#        driver-class-name: com.mysql.cj.jdbc.Driver



#      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
#      username: root                                      #数据库用户名
#      password: root                                    #数据库密码
#      url: jdbc:mysql://192.168.201.43:6036/bob?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=true&serverTimezone=GMT%2B8
#      username: root                                      #数据库用户名
#      password: Ggkj_1688
      db-type: com.alibaba.druid.pool.DruidDataSource     #数据源类型启用Druid
      driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver            #驱动 JDBC连接Mysql5需用com.mysql.jdbc.Driver  JDBC连接Mysql6需用com.mysql.cj.jdbc.Driver，同时需要指定时区serverTimezone
      filters: stat                                       #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      max-active: 20                                      #最大连接池数量maxPoolSize
      initial-size: 1                                     #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-wait: 60000                                     #获取连接时最大等待时间，单位毫秒
      min-idle: 1                                         #最小连接池数量minPoolSize
      time-between-eviction-runs-millis: 60000            #1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'                        #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      test-while-idle: true                               #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-return: false                               #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false                               #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: false                     #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-open-prepared-statements: 20                    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"         #形如：http://192.168.0.199:8808/druid/sql.html 用户名及密码都为admin就可查看 内置监控页面 这个不受限制 http://127.0.0.1:8801/druid/login.html
        login-username: admin
        login-password: admin
        allow:          #允许所有IP访问解决you are not permitted to view this page
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000





mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: github.com.bobgit.study.pinyin.model



logging:
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  level:
    root: info
    # logging.level.mapper类所在包位置=debug mybatis打印sql语句
    github.com.bobgit.study.pinyin.dao: debug
#    github.com.bobgit.study.pinyin.interceptor: info
    org:
      springframework:
        security: info
        web: info

#范围路径 比如：/admin
adminPath:
interceptor:
  # 后台管理记录拦截器
  enabled: true
  addPathPatterns: >
    ${adminPath}/**
  excludePathPatterns: >
    ${adminPath}/patient,
    ${adminPath}/rongCloud/**,
    ${adminPath}/desktop,
    ${adminPath}/sys/online/count,
    ${adminPath}/**/treeData,
    ${adminPath}/file/**,
    ${adminPath}/tags/*,
    ${adminPath}/msg/**


#
## ===========================================================================
## SchedulerFactoryBean基本配置
## ===========================================================================
##启动延迟n秒
#spring.quartz.startup-delay=1
##是否重写已存在的job
#spring.quartz.overwrite-existing-jobs=true
##是否自动启动
#spring.quartz.auto-startup=true
##quartz集群配置
## ===========================================================================
## Configure Main Scheduler Properties 调度器属性
## ===========================================================================
##调度标识名 集群中每一个实例都必须使用相同的名称
#spring.quartz.properties.org.quartz.scheduler.instanceName = DefaultQuartzScheduler
##ID设置为自动获取 每一个必须不同
#spring.quartz.properties.org.quartz.scheduler.instanceId = AUTO
#
##============================================================================
## Configure ThreadPool
##============================================================================
##线程池的实现类（一般使用SimpleThreadPool即可满足几乎所有用户的需求）
#spring.quartz.properties.org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
##指定线程数，至少为1（无默认值）(一般设置为1-100直接的整数合适)
#spring.quartz.properties.org.quartz.threadPool.threadCount = 25
##设置线程的优先级（最大为java.lang.Thread.MAX_PRIORITY 10，最小为Thread.MIN_PRIORITY 1，默认为5）
#spring.quartz.properties.org.quartz.threadPool.threadPriority = 5
##============================================================================
## Configure JobStore
##============================================================================
## 触发失败阈值，未超过触发时间60s则直接触发，若超过则失火，log信息Handling 1 trigger(s) that missed their scheduled fire-time.
#spring.quartz.properties.org.quartz.jobStore.misfireThreshold = 60000
##数据保存方式为数据库持久化
#spring.quartz.properties.org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
##数据库代理类，一般org.quartz.impl.jdbcjobstore.StdJDBCDelegate可以满足大部分数据库
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
##JobDataMaps是否都为String类型
#spring.quartz.properties.org.quartz.jobStore.useProperties = false
##表的前缀，默认QRTZ_
#spring.quartz.properties.org.quartz.jobStore.tablePrefix = QRTZ_
##是否加入集群
#spring.quartz.properties.org.quartz.jobStore.isClustered = true
##调度实例失效的检查时间间隔
#spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval = 20000
##名称必须与下方org.quartz.dataSource.@Name@.xxx一致
#spring.quartz.properties.org.quartz.jobStore.dataSource = myDS
##============================================================================
## Configure Datasources
##============================================================================
##数据库引擎
#spring.quartz.properties.org.quartz.dataSource.myDS.driver = com.mysql.cj.jdbc.Driver
##数据库连接
#spring.quartz.properties.org.quartz.dataSource.myDS.URL = jdbc:mysql://xxxxxxxxxx
##数据库用户
#spring.quartz.properties.org.quartz.dataSource.myDS.user = root
##数据库密码
#spring.quartz.properties.org.quartz.dataSource.myDS.password = xxxxxx
##允许最大连接
#spring.quartz.properties.org.quartz.dataSource.myDS.maxConnections = 5
##验证查询sql,可以不设置
#spring.quartz.properties.org.quartz.dataSource.myDS.validationQuery=select 0 from dual
#
#
